---
- hosts: linux
  become: yes
  tasks:
    - name: Print a list of cmd output.
      shell: |
        df -h 
        ip address show
      register: out
    - name: Register with debug  
      debug:
        var: out.stdout_lines
